# Generated by Django 4.1.1 on 2023-11-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('subject1', models.CharField(max_length=50)),
                ('subject2', models.CharField(max_length=50)),
                ('subject3', models.CharField(max_length=50)),
                ('subject4', models.CharField(max_length=50)),
                ('subject5', models.CharField(max_length=50)),
                ('score1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score2', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score4', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score5', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student_passport', models.FileField(upload_to='passports/')),
            ],
        ),
    ]
